//go:build ignore

// gen-docs.go generates two pieces of Vessel's docs site from the real
// source of truth so they cannot drift from the binary:
//
//  1. docs/src/content/docs/cli-reference.mdx, walked from cmd's actual
//     Cobra command tree (cmd.RootCommand()).
//  2. The flag table inside docs/src/content/docs/configuration.mdx and the
//     RBAC matrix inside docs/src/content/docs/authentication-and-roles.mdx,
//     from internal/auth.Policies.
//
// Run via `make docs-cli`, which is `go run scripts/gen-docs.go`. It is
// idempotent: running it twice in a row produces byte-identical output.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"github.com/0funct0ry/vessel/cmd"
	"github.com/0funct0ry/vessel/internal/auth"
)

const (
	cliReferencePath = "docs/src/content/docs/cli-reference.mdx"
	authPagePath     = "docs/src/content/docs/authentication-and-roles.mdx"
	configPagePath   = "docs/src/content/docs/configuration.mdx"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-docs:", err)
		os.Exit(1)
	}
}

func run() error {
	root := cmd.RootCommand()

	if err := writeFile(cliReferencePath, renderCLIReference(root)); err != nil {
		return err
	}
	if err := replaceMarked(configPagePath, "VESSEL_CONFIG_TABLE", renderFlagTable(findCommand(root, "serve"))); err != nil {
		return err
	}
	if err := replaceMarked(authPagePath, "VESSEL_RBAC_TABLE", renderRBACTable(auth.Policies)); err != nil {
		return err
	}
	fmt.Println("gen-docs: wrote", cliReferencePath)
	fmt.Println("gen-docs: updated flag table in", configPagePath)
	fmt.Println("gen-docs: updated RBAC table in", authPagePath)
	return nil
}

// ---- CLI reference ----

func renderCLIReference(root *cobra.Command) string {
	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("title: CLI reference\n")
	b.WriteString("description: Generated from the Cobra command definitions on every build, so it cannot drift from the binary you have installed.\n")
	b.WriteString("---\n\n")
	b.WriteString("import { Aside } from '@astrojs/starlight/components';\n\n")
	b.WriteString("By the end of this page you will know every subcommand and flag `vessel` has, straight from its own command definitions.\n\n")
	b.WriteString("<Aside type=\"note\">\n")
	b.WriteString("This page is generated by `make docs-cli` from `cmd`'s Cobra command tree — do not edit it by hand, edit the command definitions in `cmd/*.go` instead.\n")
	b.WriteString("</Aside>\n\n")

	var commands []*cobra.Command
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		commands = append(commands, c)
		kids := append([]*cobra.Command{}, c.Commands()...)
		sort.Slice(kids, func(i, j int) bool { return kids[i].Name() < kids[j].Name() })
		for _, k := range kids {
			if k.Hidden {
				continue
			}
			walk(k)
		}
	}
	walk(root)

	for _, c := range commands {
		use := fullUse(c)
		b.WriteString("## `" + use + "`\n\n")
		if c.Short != "" {
			b.WriteString(c.Short + "\n\n")
		}
		if c.Long != "" && c.Long != c.Short {
			b.WriteString(c.Long + "\n\n")
		}
		if table := renderFlagTable(c); table != "" {
			b.WriteString(table + "\n")
		}
	}

	return b.String()
}

func fullUse(c *cobra.Command) string {
	name := strings.Fields(c.Use)[0]
	if c.Parent() == nil {
		return name
	}
	return fullUse(c.Parent()) + " " + name
}

func renderFlagTable(c *cobra.Command) string {
	if c == nil {
		return ""
	}
	var flags []*pflag.Flag
	c.Flags().VisitAll(func(f *pflag.Flag) {
		if f.Name == "config" {
			return // every leaf command carries this identically; not worth repeating per-command
		}
		flags = append(flags, f)
	})
	if len(flags) == 0 {
		return ""
	}
	sort.Slice(flags, func(i, j int) bool { return flags[i].Name < flags[j].Name })

	var b strings.Builder
	b.WriteString("| Flag | Default | Description |\n")
	b.WriteString("| --- | --- | --- |\n")
	for _, f := range flags {
		def := f.DefValue
		if def == "" {
			def = "*(none)*"
		}
		b.WriteString(fmt.Sprintf("| `--%s` | `%s` | %s |\n", f.Name, def, escapeCell(f.Usage)))
	}
	return b.String()
}

func findCommand(root *cobra.Command, name string) *cobra.Command {
	for _, c := range root.Commands() {
		if c.Name() == name {
			return c
		}
	}
	return nil
}

func escapeCell(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}

// ---- RBAC matrix ----

func renderRBACTable(policies []auth.Policy) string {
	sorted := append([]auth.Policy{}, policies...)
	sort.SliceStable(sorted, func(i, j int) bool {
		if sorted[i].Path != sorted[j].Path {
			return sorted[i].Path < sorted[j].Path
		}
		return sorted[i].Method < sorted[j].Method
	})

	var b strings.Builder
	b.WriteString("| Method | Path | Role | Capability |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, p := range sorted {
		if !p.Implemented {
			continue
		}
		b.WriteString(fmt.Sprintf("| %s | `%s` | `%s` | `%s` |\n", p.Method, p.Path, p.Role, p.Capability))
	}
	return b.String()
}

// ---- shared marker-region replace ----

func replaceMarked(path, marker, body string) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	start := "{/* " + marker + "_START */}"
	end := "{/* " + marker + "_END */}"
	re := regexp.MustCompile(regexp.QuoteMeta(start) + `[\s\S]*?` + regexp.QuoteMeta(end))
	if !re.Match(raw) {
		return fmt.Errorf("%s: markers %s/%s not found", path, start, end)
	}
	replacement := start + "\n" + generatedComment(marker) + "\n" + strings.TrimRight(body, "\n") + "\n" + end
	out := re.ReplaceAll(raw, []byte(escapeReplacement(replacement)))
	return os.WriteFile(path, out, 0o644)
}

// escapeReplacement neutralizes Go regexp's $-expansion in ReplaceAll, since
// the generated table can legitimately contain a literal "$".
func escapeReplacement(s string) string {
	return strings.ReplaceAll(s, "$", "$$")
}

func generatedComment(marker string) string {
	switch marker {
	case "VESSEL_CONFIG_TABLE":
		return "{/* generated by `make docs-cli` from cmd/serve.go's addServeFlags — do not edit by hand */}"
	case "VESSEL_RBAC_TABLE":
		return "{/* generated by `make docs-cli` from internal/auth/rbac.go's Policies table — do not edit by hand */}"
	default:
		return ""
	}
}

func writeFile(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}
